
//
//  This tool reads ARToolKit pattern files (variable size) and saves them
//  as Portable Pixmap (.ppm) files.
//
//  Usage: patt2ppm <infilename> <outfilename> [width=16] [height=16]
//
//  Thanks to Antonio Bleile for contributing the PPM writer code

#include <charconv>
#include <cstddef>
#include <cstdlib>
#include <filesystem>
#include <fstream>
#include <iostream>
#include <optional>
#include <span>
#include <string_view>
#include <vector>

static constexpr int MAX_IMAGE_DIM = 65535;

struct ImageDimensions {
    int width;
    int height;
};

[[nodiscard]] static std::optional<int> parseDimension(std::string_view str) noexcept {
    int value{};
    const auto [ptr, ec] = std::from_chars(str.data(), str.data() + str.size(), value);
    if (ec != std::errc{} || ptr != str.data() + str.size())
        return std::nullopt;
    if (value <= 0 || value > MAX_IMAGE_DIM)
        return std::nullopt;
    return value;
}

// Reads an ARToolKit pattern file.
// The file stores pixel values channel by channel (R plane, G plane, B plane),
// each as whitespace-separated integers. Returns RGB-interleaved pixel data,
// or nullopt on failure to open the file.
[[nodiscard]] static std::optional<std::vector<unsigned char>>
readMarkerFile(const std::filesystem::path& path, const ImageDimensions dims)
{
    std::ifstream file{path};
    if (!file)
        return std::nullopt;

    const std::size_t numPix =
        static_cast<std::size_t>(dims.width) * static_cast<std::size_t>(dims.height);
    std::vector<unsigned char> pixels(numPix * 3);

    for (int channel = 0; channel < 3; ++channel) {
        for (int y = 0; y < dims.height; ++y) {
            for (int x = 0; x < dims.width; ++x) {
                int value{};
                if (!(file >> value))
                    return pixels;

                const std::size_t offset =
                    3 * (static_cast<std::size_t>(x) +
                         static_cast<std::size_t>(y) * static_cast<std::size_t>(dims.width)) +
                    static_cast<std::size_t>(channel);
                pixels[offset] = static_cast<unsigned char>(value);
            }
        }
    }

    return pixels;
}

// Writes pixel data as a binary PPM file.
// data must contain width * height * 3 bytes (RGB interleaved).
[[nodiscard]] static bool
writePPM(const std::filesystem::path& path,
         std::span<const unsigned char> data,
         const ImageDimensions dims)
{
    std::ofstream file{path, std::ios::binary};
    if (!file) {
        std::cerr << "Could not open file " << path << " for writing\n";
        return false;
    }

    file << "P6\n# generated by patt_to_ppm\n"
         << dims.width << ' ' << dims.height << "\n255\n";

    // reinterpret_cast is required: ostream::write takes const char*
    file.write(reinterpret_cast<const char*>(data.data()),
               static_cast<std::streamsize>(data.size()));

    if (!file) {
        std::cerr << "Error writing pixel data to " << path << '\n';
        return false;
    }

    return true;
}

int main(int argc, char** argv)
{
    const std::span<char* const> args{argv, static_cast<std::size_t>(argc)};

    if (args.size() < 3) {
        std::cerr << "ERROR: too few parameters\n"
                  << "Usage: "   << args[0] << " infilename outfilename [width=16] [height=16]\n"
                  << "Example: " << args[0] << " patt.hiro patt_hiro.ppm 32 32\n";
        return EXIT_FAILURE;
    }

    ImageDimensions dims{.width = 16, .height = 16};

    if (args.size() >= 4) {
        const auto w = parseDimension(args[3]);
        if (!w) {
            std::cerr << "ERROR: invalid width '" << args[3]
                      << "' (must be 1.." << MAX_IMAGE_DIM << ")\n";
            return EXIT_FAILURE;
        }
        dims.width = *w;
    }

    if (args.size() >= 5) {
        const auto h = parseDimension(args[4]);
        if (!h) {
            std::cerr << "ERROR: invalid height '" << args[4]
                      << "' (must be 1.." << MAX_IMAGE_DIM << ")\n";
            return EXIT_FAILURE;
        }
        dims.height = *h;
    }

    const auto pixels = readMarkerFile(args[1], dims);
    if (!pixels) {
        std::cerr << "ERROR: could not read marker file '" << args[1] << "'\n";
        return EXIT_FAILURE;
    }

    if (!writePPM(args[2], std::span<const unsigned char>{*pixels}, dims))
        return EXIT_FAILURE;

    return EXIT_SUCCESS;
}
