
//
//
//  This tool will read ARToolKit pattern files (with variable size) and save
//  them as Portable Pixmap (.ppm) files.
//
//  Usage: PATT_to_PPM [infilename] [outfilename] [width] [height]
//
//
//  Thanks to Antonio Bleile for contributing the PPM writer code
//


#include <stdio.h>
#include <assert.h>
#include <stdlib.h>
#include <cstddef>
#include <cerrno>
#include <climits>


static constexpr int MAX_IMAGE_DIM = 65535;


// Returns the parsed dimension on success, or -1 on error.
// Rejects non-positive values, values above MAX_IMAGE_DIM, and non-numeric input.
static int parseDimension(const char* str) {
    char* end = nullptr;
    errno = 0;
    const long value = strtol(str, &end, 10);
    if (errno != 0 || end == str || *end != '\0')
        return -1;
    if (value <= 0 || value > MAX_IMAGE_DIM)
        return -1;
    return static_cast<int>(value);
}


char
skipSpaces(FILE* fp)
{
	char ch = ' ';

	while( ch==' ' && !feof(fp))
		ch = fgetc(fp);

	return ch;
}


bool
readNumber(FILE* fp, char* buffer, int maxLen)
{
	char ch = 0;
	int i=0;

	do {
		ch = fgetc(fp);
		if(ch>='0' && ch<='9')
			buffer[i++] = ch;
	} while(!feof(fp) && i<maxLen-1 && ch!=' ');


	buffer[i++] = 0;
	return i<maxLen && !feof(fp);
}


// Precondition: width > 0 && height > 0 (validated by caller)
bool
writePPM( const char *fileName, const unsigned char *data, int width, int height )
{
	assert(width > 0 && height > 0);

	FILE *file = fopen( fileName, "wb" );
	if( !file ){
		printf( "Could not open file %s for writing\n", fileName );
		return false;
	}

	fprintf( file, "P6\n# generated by patt_to_ppm\n%d %d\n255\n", width, height );

	const std::size_t numBytes = static_cast<std::size_t>(width) * static_cast<std::size_t>(height) * 3;
	const std::size_t written = fwrite( data, 1, numBytes, file );

	fclose( file );

	if (written != numBytes) {
		printf( "Error: wrote %zu of %zu bytes to %s\n", written, numBytes, fileName );
		return false;
	}

	return true;
}


// Precondition: nMarkerWidth > 0 && nMarkerHeight > 0 (validated by caller)
unsigned char *
readMarkerFile(const char* nFileName, int nMarkerWidth, int nMarkerHeight)
{
	assert(nMarkerWidth > 0 && nMarkerHeight > 0);

	FILE* fp = fopen(nFileName, "r");

	if(!fp)
		return NULL;

	const int strMax = 256;
	const std::size_t numPix = static_cast<std::size_t>(nMarkerWidth) * static_cast<std::size_t>(nMarkerHeight);
	unsigned char* pixels24 = new unsigned char[numPix * 3];
	char str[strMax+1];

	for(int channel=0; channel<3; ++channel)
	{
		for(int y=0; y<nMarkerHeight; ++y)
		{
			for(int x=0; x<nMarkerWidth; ++x)
			{
				str[0] = skipSpaces(fp);
				readNumber(fp, str+1, strMax);
				int value = atoi(str);
				const std::size_t offset = 3 * (static_cast<std::size_t>(x) + static_cast<std::size_t>(y) * nMarkerWidth) + channel;
				assert(offset < numPix * 3);
				pixels24[offset] = static_cast<unsigned char>(value);
			}
		}
}

	fclose(fp);

	return pixels24;
}


int main(int argc, char** argv)
{
	int width = 16, height = 16;

	if(argc<3)
	{
		printf("ERROR: to few parameters\n");
		printf("Usage: %s infilename outfilename [width=16] [height=16]\n", argv[0] );
		printf("Example: %s patt.hiro patt_hiro.ppm 32 32\n", argv[0] );
		return EXIT_FAILURE;
	}

	const char	*inName = argv[1],
				*outName = argv[2];

	if( argc >= 4 )
	{
		width = parseDimension(argv[3]);
		if (width < 0)
		{
			printf("ERROR: invalid width '%s' (must be 1..%d)\n", argv[3], MAX_IMAGE_DIM);
			return EXIT_FAILURE;
		}
	}
	if( argc >= 5 )
	{
		height = parseDimension(argv[4]);
		if (height < 0)
		{
			printf("ERROR: invalid height '%s' (must be 1..%d)\n", argv[4], MAX_IMAGE_DIM);
			return EXIT_FAILURE;
		}
	}

	unsigned char* patternImage = readMarkerFile(inName, width, height);

	if( patternImage )
	{
		writePPM( outName, patternImage, width, height );
	}	

	delete[] patternImage;

	return EXIT_SUCCESS;
}
